#!/bin/sh

### Uncomment it if you dont want to execute ###
# RUN_DEBLOAT=false # removes snap firefox and snap
KEYBINDINGS_SETUP=false   # sets keybindings
# APPLICATION_SETUP=false # installs applications
# DOTFILES_SETUP=false    # sets up dotfile i.e .bashrc,etc..
PROJECTS_SETUP=false      # downloads my git projects
# GNOME_EXTENSION_SETUP=false

### Config to add hosts list /etc/hosts
#  1)Unified hosts = (adware +malware)
#  2)Unified hosts + fakenews
#  3)Unified hosts + gambling
#  4)Unified hosts + porn
#  5)Unified hosts + social
#  6)Unified hosts + fakenews + gambling
#  7)Unified hosts + fakenews + porn
#  8)Unified hosts + fakenews + social
#  9)Unified hsots + gambling + porn
# 10)Unified hosts + gambling + social
# 11)Unified hosts + porn + social
# 12)Unified hosts + fakenews + gambling + porn
# 13)Unified hosts + fakenews + gambling + social
# 14)Unified hosts + fakenews + porn + social
# 15))Unified hosts + fakenews + gambling + porn + social"
## put your option in HOST_OPTION
## Uncomment if you don't want to run
# RUN_HOST_SH=false
HOST_OPTION=12

# Uncomment it if you don't want to install
 INSTALL_VSCODE=false
INSTALL_GO_COMPILER=false
INSTALL_TEAMS=false
 INSTALL_NOISETORCH=false

 INSTALL_TELEGRAM=false
TELEGRAM_INSTALL_DIR="~/app_builds"

INSTALL_XMRIG=false
XMRIG_INSTALL_DIR="~/app_builds"

INSTALL_MONERO_WALLET=false
MONERO_WALLET_INSTALL_DIR="~/app_builds"

 INSTALL_WATERFOX=false
WATERFOX_INSTALL_DIR="/usr/local/bin"

 INSTALL_VENTOY=false
VENTOY_INSTALL_DIR="~/app_builds"

### Temporary directory to download the files
TEMP_DIR="~/tmp"


