#!/bin/bash

set -x -e

mkdir -p "${HOME}/.ssh"
pushd "${HOME}/.ssh"
ssh-keygen -t ed25519 -C "jagadeeshanmsj@github.com"
ssh-add id_ed25519
xclip -i id_ed25519.pub -selection clipboard
echo "ssh public key copied to clipboard"
echo "Now add the public key to github"

echo "To push repository, run $ git remote set-url origin git@github.com:<user-name>/<project-name>.git"
echo "Bye"
popd
