#!/bin/bash


### Bash Exports ### {{{
export CLICOLOR="YES"       ## Color 'ls', etc.
export EDITOR=nvim           ## Set default editor


### HIST EXPORTS  ###
export HISTCONTROL="ignoredups"             # ignore duplicates(store command once)
export HISTCONTROL="ignoreboth"
export HISTFILESIZE=                        # NOTE: effectively "unlimited", since it's defined but without value
export HISTSIZE=                            # https://superuser.com/questions/137438/how-to-unlimited-bash-shell-history
                                            # https://unix.stackexchange.com/a/20925
export HISTIGNORE='ls:bg:fg:history'

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

